FROM node:18-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .
COPY .env.prod .env.local

RUN npm run build

FROM node:18-alpine AS runner
WORKDIR /app

COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app/.env.local ./
ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

CMD ["node", "--dns-result-order=ipv4first", "build/index.js", "--host", "0.0.0.0", "--port", "3000"]