name: Screenshots

on:
  pull_request:
  workflow_dispatch:

jobs:
  screenshots:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Start mock API server
        run: node e2e/mock-api.mjs &

      - name: Start dev server
        run: |
          OPENAI_BASE_URL=http://localhost:18080/v1 OPENAI_API_KEY=mock-key npm run dev &
          for i in $(seq 1 30); do
            if curl -s -o /dev/null -w "%{http_code}" http://localhost:5173/ | grep -q "200"; then
              echo "Dev server is up"
              exit 0
            fi
            echo "Waiting for dev server... (attempt $i)"
            sleep 2
          done
          echo "Dev server did not start in time"
          exit 1

      - name: Take screenshots
        run: node e2e/take-screenshots.mjs

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: e2e/screenshots/
          retention-days: 30
