{{- if .Values.externalSecrets.enabled }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  labels: {{ include "labels.standard" . | nindent 4 }}
  name: {{ include "name" $ }}-external-secret
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.secretName }}
  data:
    {{- range $key, $value := .Values.externalSecrets.parameters }}
    - secretKey: {{ $key | quote }}
      remoteRef:
        key: {{ $value | quote }}
    {{- end }}
{{- end }}
