apiVersion: v1
kind: Service
metadata:
  name: "{{ include "name" . }}"
  annotations: {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "labels.standard" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector: {{ include "labels.standard" . | nindent 4 }}
  type: {{.Values.service.type}}
