FROM node:20
WORKDIR /app

# Install required build tools
RUN apt-get update && apt-get install -y \
    git cmake build-essential python3 \
 && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install

COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]
